export const FETCH_ALL_CATEGORIES = 'FETCH_ALL_CATEGORIES';
export const FETCH_ALL_CATEGORIES_START = 'FETCH_ALL_CATEGORIES_START';
export const FETCH_ALL_CATEGORIES_SUCCESS = 'FETCH_ALL_CATEGORIES_SUCCESS';
export const FETCH_ALL_CATEGORIES_FAIL = 'FETCH_ALL_CATEGORIES_FAIL';

export const FETCH_ALL_PRODUCTS = 'FETCH_ALL_PRODUCTS';
export const FETCH_ALL_PRODUCTS_START = 'FETCH_ALL_PRODUCTS_START';
export const FETCH_ALL_PRODUCTS_SUCCESS = 'FETCH_ALL_PRODUCTS_SUCCESS';
export const FETCH_ALL_PRODUCTS_FAIL = 'FETCH_ALL_PRODUCTS_FAIL';

export const FETCH_TOP_SELLERS = 'FETCH_TOP_SELLERS';
export const FETCH_TOP_SELLERS_START = 'FETCH_TOP_SELLERS_START';
export const FETCH_TOP_SELLERS_SUCCESS = 'FETCH_TOP_SELLERS_SUCCESS';
export const FETCH_TOP_SELLERS_FAIL = 'FETCH_TOP_SELLERS_FAIL';

export const FETCH_NEW_ARRIVALS = 'FETCH_NEW_ARRIVALS';
export const FETCH_NEW_ARRIVALS_START = 'FETCH_NEW_ARRIVALS_START';
export const FETCH_NEW_ARRIVALS_SUCCESS = 'FETCH_NEW_ARRIVALS_SUCCESS';
export const FETCH_NEW_ARRIVALS_FAIL = 'FETCH_NEW_ARRIVALS_FAIL';

export const FETCH_CATEGORY_BY_SLUG = 'FETCH_CATEGORY_BY_SLUG';
export const FETCH_CATEGORY_BY_SLUG_START = 'FETCH_CATEGORY_BY_SLUG_START';
export const FETCH_CATEGORY_BY_SLUG_SUCCESS = 'FETCH_CATEGORY_BY_SLUG_SUCCESS';
export const FETCH_CATEGORY_BY_SLUG_FAIL = 'FETCH_CATEGORY_BY_SLUG_FAIL';

export const FETCH_CATEGORY_LIST = 'FETCH_CATEGORY_LIST';
export const FETCH_CATEGORY_LIST_START = 'FETCH_CATEGORY_LIST_START';
export const FETCH_CATEGORY_LIST_SUCCESS = 'FETCH_CATEGORY_LIST_SUCCESS';
export const FETCH_CATEGORY_LIST_FAIL = 'FETCH_CATEGORY_LIST_FAIL';

export const FETCH_PRODUCT_BY_SLUG = 'FETCH_PRODUCT_BY_SLUG';
export const FETCH_PRODUCT_BY_SLUG_START = 'FETCH_PRODUCT_BY_SLUG_START';
export const FETCH_PRODUCT_BY_SLUG_SUCCESS = 'FETCH_PRODUCT_BY_SLUG_SUCCESS';
export const FETCH_PRODUCT_BY_SLUG_FAIL = 'FETCH_PRODUCT_BY_SLUG_FAIL';

export const ADD_TO_CART = 'ADD_TO_CART';
