<?php

return [
	"mainMenus" => [
		[
			"name" => "Clothing",
			"children" => [
				["name" => "All Products"],
				["name" => "Suits"],
				["name" => "Shirts"],
				["name" => "Trousers"],
				["name" => "Jackets"],
				["name" => "Jeans"],
				["name" => "Coats"],
				["name" => "Polos"],
				["name" => "Pullovers / Knit"],
				["name" => "Sweatshirts & More"],
				["name" => "T-shirts"],
			],
			"brands" => [
				["name" => "Tommy Hilfiger"],
				["name" => "Pepe Jeans"],
				["name" => "LTB"],
				["name" => "Khujo"],
				["name" => "Ben Sherman"],
				["name" => "Mishomo"],
				["name" => "Calvin Klein"],
				["name" => "Marc O'Polo"],
				["name" => "Puma"],
				["name" => "New Zealand Auckland"],
			]
		],
		[
			"name" => "Shoes",
			"children" => [
				["name" => "All Products"],
				["name" => "Business Shoes"],
				["name" => "Loafers & More"],
				["name" => "Sandals / Thong Sandals"],
				["name" => "Laced Shoes"],
				["name" => "Shoe Accesories"],
				["name" => "Sneakers"],
				["name" => "Sports Shoes"],
				["name" => "Boots / Ankle Boots"],
			],
			"brands" => [
				["name" => "Tommy Hilfiger"],
				["name" => "Mishumo"],
				["name" => "Otto Kern"],
				["name" => "Timberland"],
				["name" => "Cafe Noir"],
				["name" => "U.S. Polo Assn."],
				["name" => "New Zealand Auckland"],
				["name" => "Gaastra"],
				["name" => "Puma"],
				["name" => "Gola"],
				["name" => "Bjorn Borg"],
			]
		],
		[
			"name" => "Accesories",
			"children" => [
				["name" => "All Products"],
				["name" => "Purses"],
				["name" => "Belts"],
				["name" => "Home & Spa"],
				["name" => "Suitcases"],
				["name" => "Ties"],
				["name" => "Cufflinks"],
				["name" => "Beanies & More"],
				["name" => "Scarves & More"],
				["name" => "Bags"],
			],
			"brands" => [
				["name" => "Tommy Hilfiger"],
				["name" => "Mishumo"],
				["name" => "Calvin Klein"],
				["name" => "Milano"],
				["name" => "Roeckl"],
				["name" => "Pierre Cardin"],
				["name" => "New Zealand Auckland"],
				["name" => "Tom Tailor"],
				["name" => "Puma"],
				["name" => "O'Neill"],
			]
		],
		[
			"name" => "Underwear",
			"children" => [
				["name" => "All Products"],
				["name" => "Boxers"],
				["name" => "Sleepwear"],
				["name" => "Briefs"],
				["name" => "Spcks"],
			],
			"brands" => [
				["name" => "Tommy Hilfiger"],
				["name" => "Calvin Klein"],
				["name" => "Mishumo"],
				["name" => "Pepe Jeans"],
				["name" => "New Zealand Auckland"],
				["name" => "Reebok"],
				["name" => "Schiesser"],
				["name" => "Marc O'Polo"],
				["name" => "Ben Sherman"],
				["name" => "Karl Lagerfeld"],
			]
		],
		["name" => "What's New", "children" => [
			["name" => "Clothing", "children" => [
				["name" => "All Products"],
				["name" => "Suits"],
				["name" => "Shirts"],
				["name" => "Trousers"],
				["name" => "Jackets"],
				["name" => "Jeans"],
				["name" => "Coats"],
				["name" => "Polos"],
				["name" => "Pullovers / Knit"],
				["name" => "Sweatshirts & More"],
				["name" => "T-shirts"],
			]],
			["name" => "Shoes", "children" => [
				["name" => "All Products"],
				["name" => "Business Shoes"],
				["name" => "Loafers & More"],
				["name" => "Sandals / Thong Sandals"],
				["name" => "Laced Shoes"],
				["name" => "Shoe Accesories"],
				["name" => "Sneakers"],
				["name" => "Sports Shoes"],
				["name" => "Boots / Ankle Boots"],
			]],
			["name" => "Accesories", "children" => [
				["name" => "All Products"],
				["name" => "Purses"],
				["name" => "Belts"],
				["name" => "Home & Spa"],
				["name" => "Suitcases"],
				["name" => "Ties"],
				["name" => "Cufflinks"],
				["name" => "Beanies & More"],
				["name" => "Scarves & More"],
				["name" => "Bags"],
			]],
			["name" => "Underwear", "children" => [
				["name" => "All Products"],
				["name" => "Boxers"],
				["name" => "Sleepwear"],
				["name" => "Briefs"],
				["name" => "Spcks"],
			]],
		]],
		["name" => "Kids", "children" => []],
		["name" => "Brands A-Z", "children" => []],
	]
];
