<?php

return [
	"mainMenus" => [
		["name" => "Clothing", "children" => [
			["name" => "All Products"],
			["name" => "Suits"],
			["name" => "Shirts"],
			["name" => "Trousers"],
			["name" => "Jackets"],
			["name" => "Jeans"],
			["name" => "Coats"],
			["name" => "Polos"],
			["name" => "Pullovers / Knit"],
			["name" => "Sweatshirts & More"],
			["name" => "T-shirts"],
		]],
		["name" => "Shoes", "children" => [
			["name" => "All Products"],
			["name" => "Business Shoes"],
			["name" => "Loafers & More"],
			["name" => "Sandals / Thong Sandals"],
			["name" => "Laced Shoes"],
			["name" => "Shoe Accesories"],
			["name" => "Sneakers"],
			["name" => "Sports Shoes"],
			["name" => "Boots / Ankle Boots"],
		]],
		["name" => "Accesories", "children" => [
			["name" => "All Products"],
			["name" => "Purses"],
			["name" => "Belts"],
			["name" => "Home & Spa"],
			["name" => "Suitcases"],
			["name" => "Ties"],
			["name" => "Cufflinks"],
			["name" => "Beanies & More"],
			["name" => "Scarves & More"],
			["name" => "Bags"],
		]],
		["name" => "Userwear", "children" => [
			["name" => "All Products"],
			["name" => "Boxers"],
			["name" => "Sleepwear"],
			["name" => "Briefs"],
			["name" => "Spcks"],
		]],
		["name" => "What's New", "children" => [
			["name" => "Clothing", "children" => [
				["name" => "All Products"],
				["name" => "Suits"],
				["name" => "Shirts"],
				["name" => "Trousers"],
				["name" => "Jackets"],
				["name" => "Jeans"],
				["name" => "Coats"],
				["name" => "Polos"],
				["name" => "Pullovers / Knit"],
				["name" => "Sweatshirts & More"],
				["name" => "T-shirts"],
			]],
			["name" => "Shoes", "children" => [
				["name" => "All Products"],
				["name" => "Business Shoes"],
				["name" => "Loafers & More"],
				["name" => "Sandals / Thong Sandals"],
				["name" => "Laced Shoes"],
				["name" => "Shoe Accesories"],
				["name" => "Sneakers"],
				["name" => "Sports Shoes"],
				["name" => "Boots / Ankle Boots"],
			]],
			["name" => "Accesories", "children" => [
				["name" => "All Products"],
				["name" => "Purses"],
				["name" => "Belts"],
				["name" => "Home & Spa"],
				["name" => "Suitcases"],
				["name" => "Ties"],
				["name" => "Cufflinks"],
				["name" => "Beanies & More"],
				["name" => "Scarves & More"],
				["name" => "Bags"],
			]],
			["name" => "Userwear", "children" => [
				["name" => "All Products"],
				["name" => "Boxers"],
				["name" => "Sleepwear"],
				["name" => "Briefs"],
				["name" => "Spcks"],
			]],
		]],
		["name" => "Kids", "children" => []],
		["name" => "Brands A-Z", "children" => []],
	]
];
